services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gwd\Bundle\ContactBundle\Controller\:
    resource: '../../Controller/*'
    public: true
    tags: ['controller.service_arguments']